route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'smtp.example.com'
    from: 'smtp.example.com'
    smarthost: smtp.example.com:587
    auth_username: 'user@example.com'
    auth_identity: 'user@example.com'
    auth_password: 'X'