version: "3"

services:
  nginx:
    image: nginx:1.23.1
    ports: 
      - '127.0.0.1:80:80'
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./www:/var/www/"
      - "./logs:/var/log/nginx"
  php:
    build: .
    volumes:
      - "./www:/var/www/"
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://nginx | grep -c works > /dev/null"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 10s