version: '3.2'
services:
  prometheus: 
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 127.0.0.1:9090:9090
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.3.1
    hostname: "prometheus-vm"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)

    ports:
      - 127.0.0.1:9100:9100
    restart: always

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.22.0
    ports:
      - 127.0.0.1:9115:9115
    restart: always

  grafana:
    image: grafana/grafana:9.1.1
    depends_on:
      - prometheus
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.24.0
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'